[general]
number_of_runs = 10
prefix = "S3_i"

[environment]
knowledge_graph_name="Countries/Countries_S3"
inverse_relations=false
relation_types=[]
max_degree=200
prune=true

[reward]
gamma = 0.95
lambda_factor = 0.003
 
[interaction]
interactive = true
use_entities = true
top_k = 60 
feedback_engine="roi"
error_rate = -1
pretraining_epochs=0
patients=1
fit_reward_epochs = "zero-five-ten-fifteen"
embedding_size = 16
mlp_size = 32
dropout = 0.43
learning_rate = 0.003
goal_loss_impact = 0.64
batch_size = 128

[policy_network]
hidden_size = 32
embedding_size = 32
mlp_size = 32  
use_entites = true
dropout=0.43

[training]  
num_epochs = 60
num_hops = 3
batch_size = 32
action_dropout_rate=0.2
num_rollouts_training = 20
beta=0.68
decay_rate=0.84   
learning_rate=0.005

[evaluation]
evaluation_frequency = 2
num_rollouts_test = 20
use_localization = true
roi_dir = "localization"